### ISSUE TITLE
Exception occurs when i go to localhost in browser

### ISSUE THREAD

**Issue by Zulfen** [ilytt/osu_2007#4]
Hey! When i try and run app.js with node (is that the right one? i am new to node.js), i go to localhost in chrome and it immediately throws an exception:
```
C:\Users\josh>node C:\Users\josh\Desktop\osu_2007_js-master\app.js
C:\Users\josh\Desktop\osu_2007_js-master\db\index.js:17
                connection.release();
                           ^

TypeError: Cannot read property 'release' of undefined
    at pool.getConnection (C:\Users\josh\Desktop\osu_2007_js-master\db\index.js:
17:28)
    at Handshake.onConnect (C:\Users\josh\node_modules\mysql\lib\Pool.js:58:9)
    at Handshake.<anonymous> (C:\Users\josh\node_modules\mysql\lib\Connection.js
:525:10)
    at Handshake._callback (C:\Users\josh\node_modules\mysql\lib\Connection.js:4
91:16)
    at Handshake.Sequence.end (C:\Users\josh\node_modules\mysql\lib\protocol\seq
uences\Sequence.js:83:24)
    at Protocol.handleNetworkError (C:\Users\josh\node_modules\mysql\lib\protoco
l\Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (C:\Users\josh\node_modules
\mysql\lib\Connection.js:421:18)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
```

I feel like this is a problem on my end since I am totally new to node.js. I installed three modules: express, mysql and md5. Maybe I am missing something from your instructions?
Thanks for reading!

**Comment by Zulfen** [comment]
Hold up, I don't even have nginx, I am being stupid.
Let me do that first.
